import Head from "next/head";
import Quotes from "@/components/Quotes";

export default function Home() {
  return (
    <>
      <Head>
        <title>Quotes Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid h-screen place-items-center">
        <Quotes />
      </div>
    </>
  );
}
